[package]
name = "hardback_server_lib"
version = "0.1.0"
authors = ["alanpoon"]

[dependencies]
serde="1.0"
serde_json = "1.0"
serde_derive ="1.0"
cardgame_macros = {path="../cardgame_macros"}

[lib]
name = "hardback_server_lib"
path = "src/lib.rs"